import type { PaintingCatalogEnv, PaintingModelDefinition, PaintingProvider } from './types.ts';

const OPENAI_DEFAULT_SIZES = ['1024x1024', '1536x1024', '1024x1536'];
const GOOGLE_GEMINI_FLASH_SIZES = ['1024x1024', '1248x832', '832x1248', '1344x768', '768x1344'];
const GOOGLE_GEMINI_PREVIEW_SIZES = ['1024x1024', '2048x2048', '1264x848', '848x1264', '1376x768', '768x1376'];
const GOOGLE_IMAGEN_SIZES = ['1024x1024', '2048x2048', '1200x896', '896x1200', '1376x768', '768x1376'];
const MAGNIFIC_SIZES = ['1024x1024', '1440x768', '768x1440', '1200x900', '900x1200'];

const ALL_MODELS: PaintingModelDefinition[] = [
  {
    provider: 'openai',
    modelId: 'gpt-image-2',
    label: 'GPT Image 2',
    description: 'OpenAI flagship image model for generation and editing.',
    operations: ['generate', 'edit'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsBackground: true,
    supportsCount: true,
    supportsQuality: true,
    qualityOptions: ['low', 'medium', 'high'],
    backgroundOptions: ['auto', 'transparent', 'opaque'],
    maxCount: 4,
  },
  {
    provider: 'openai',
    modelId: 'gpt-image-1.5',
    label: 'GPT Image 1.5',
    description: 'High-fidelity OpenAI image model with prompt adherence improvements.',
    operations: ['generate', 'edit'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsBackground: true,
    supportsCount: true,
    supportsQuality: true,
    qualityOptions: ['low', 'medium', 'high'],
    backgroundOptions: ['auto', 'transparent', 'opaque'],
    maxCount: 4,
  },
  {
    provider: 'openai',
    modelId: 'gpt-image-1',
    label: 'GPT Image 1',
    description: 'General-purpose OpenAI image model with edit support.',
    operations: ['generate', 'edit'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsBackground: true,
    supportsCount: true,
    supportsQuality: true,
    qualityOptions: ['low', 'medium', 'high'],
    backgroundOptions: ['auto', 'transparent', 'opaque'],
    maxCount: 4,
  },
  {
    provider: 'openai',
    modelId: 'gpt-image-1-mini',
    label: 'GPT Image 1 Mini',
    description: 'Cost-efficient OpenAI image model.',
    operations: ['generate', 'edit'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsBackground: true,
    supportsCount: true,
    supportsQuality: true,
    qualityOptions: ['low', 'medium', 'high'],
    backgroundOptions: ['auto', 'transparent', 'opaque'],
    maxCount: 4,
  },
  {
    provider: 'openai',
    modelId: 'dall-e-3',
    label: 'DALL·E 3',
    description: 'OpenAI legacy image model for generation-only workflows.',
    operations: ['generate'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsQuality: true,
    qualityOptions: ['standard', 'hd'],
    maxCount: 1,
  },
  {
    provider: 'openai',
    modelId: 'dall-e-2',
    label: 'DALL·E 2',
    description: 'Older OpenAI image model that still supports edits.',
    operations: ['generate', 'edit'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsCount: true,
    maxCount: 4,
  },
  {
    provider: 'google',
    modelId: 'gemini-2.5-flash-image',
    label: 'Gemini 2.5 Flash Image',
    description: 'Stable Gemini image generation and editing model.',
    operations: ['generate', 'edit'],
    sizes: GOOGLE_GEMINI_FLASH_SIZES,
    supportsReferenceImages: true,
  },
  {
    provider: 'google',
    modelId: 'gemini-3.1-flash-image-preview',
    label: 'Gemini 3.1 Flash Image Preview',
    description: 'Preview Gemini image model with higher resolutions and editing support.',
    operations: ['generate', 'edit'],
    sizes: GOOGLE_GEMINI_PREVIEW_SIZES,
    supportsReferenceImages: true,
  },
  {
    provider: 'google',
    modelId: 'gemini-3-pro-image-preview',
    label: 'Gemini 3 Pro Image Preview',
    description: 'Higher-end Gemini preview image model for richer generation and editing.',
    operations: ['generate', 'edit'],
    sizes: GOOGLE_GEMINI_PREVIEW_SIZES,
    supportsReferenceImages: true,
  },
  {
    provider: 'google',
    modelId: 'imagen-4.0-generate-001',
    label: 'Imagen 4 Standard',
    description: 'Google Imagen 4 standard image generation model.',
    operations: ['generate'],
    sizes: GOOGLE_IMAGEN_SIZES,
    supportsCount: true,
    maxCount: 4,
  },
  {
    provider: 'google',
    modelId: 'imagen-4.0-ultra-generate-001',
    label: 'Imagen 4 Ultra',
    description: 'Google Imagen 4 higher-end image generation model.',
    operations: ['generate'],
    sizes: GOOGLE_IMAGEN_SIZES,
    supportsCount: true,
    maxCount: 4,
  },
  {
    provider: 'google',
    modelId: 'imagen-4.0-fast-generate-001',
    label: 'Imagen 4 Fast',
    description: 'Google Imagen 4 lower-latency image generation model.',
    operations: ['generate'],
    sizes: ['1024x1024', '1376x768', '768x1376'],
    supportsCount: true,
    maxCount: 4,
  },
  {
    provider: 'google',
    modelId: 'imagen-3.0-generate-002',
    label: 'Imagen 3',
    description: 'Google Imagen 3 generation model.',
    operations: ['generate'],
    sizes: ['1024x1024', '1376x768', '768x1376'],
    supportsCount: true,
    maxCount: 4,
  },
  {
    provider: 'stability',
    modelId: 'stable-image-core',
    label: 'Stable Image Core',
    description: 'Stability standard text-to-image endpoint.',
    operations: ['generate'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsSeed: true,
    supportsNegativePrompt: true,
  },
  {
    provider: 'stability',
    modelId: 'stable-image-ultra',
    label: 'Stable Image Ultra',
    description: 'Stability higher-end text-to-image endpoint.',
    operations: ['generate'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsSeed: true,
    supportsNegativePrompt: true,
  },
  {
    provider: 'stability',
    modelId: 'stable-image-inpaint',
    label: 'Stable Image Inpaint',
    description: 'Stability image editing endpoint for prompt-guided inpainting.',
    operations: ['edit', 'remix'],
    sizes: OPENAI_DEFAULT_SIZES,
    supportsSeed: true,
    supportsReferenceImages: true,
  },
  {
    provider: 'stability',
    modelId: 'stable-image-upscale-creative',
    label: 'Stable Image Upscale Creative',
    description: 'Creative Stability upscaler for prompt-guided enhancement.',
    operations: ['upscale'],
    sizes: ['2048x2048'],
    supportsSeed: true,
    supportsNegativePrompt: true,
    supportsReferenceImages: true,
  },
  {
    provider: 'freepik',
    modelId: 'mystic',
    label: 'Mystic',
    description: 'Magnific recommended ultra-realistic async image workflow.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'flux-kontext-pro',
    label: 'Flux Kontext Pro',
    description: 'Context-aware Magnific model with optional image input support.',
    operations: ['generate', 'edit', 'remix'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    supportsReferenceImages: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'flux-2-pro',
    label: 'Flux 2 Pro',
    description: 'Professional Magnific text-to-image model with async task polling.',
    operations: ['generate', 'edit'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    supportsReferenceImages: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'flux-2-turbo',
    label: 'Flux 2 Turbo',
    description: 'Faster Magnific FLUX model for rapid iteration.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'flux-2-klein',
    label: 'Flux 2 Klein',
    description: 'Low-latency Magnific model with optional reference images.',
    operations: ['generate', 'edit'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    supportsReferenceImages: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'flux-pro-v1-1',
    label: 'Flux Pro 1.1',
    description: 'Premium FLUX image generation model.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'flux-dev',
    label: 'Flux Dev',
    description: 'High quality Magnific FLUX model for detailed generations.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'hyperflux',
    label: 'Hyperflux',
    description: 'Ultra-fast async generation model from Magnific.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'seedream-v4',
    label: 'Seedream 4',
    description: 'Fast, high-quality Seedream image generation model.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'seedream-v4-5',
    label: 'Seedream 4.5',
    description: 'Latest Seedream image generation model from Magnific.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'z-image-turbo',
    label: 'Z-Image Turbo',
    description: 'Fast Magnific image generation model for quick iterations.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsSeed: true,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'freepik',
    modelId: 'runway',
    label: 'RunWay Text-to-Image',
    description: 'RunWay image generation via Magnific.',
    operations: ['generate'],
    sizes: MAGNIFIC_SIZES,
    supportsPromptUpsampling: true,
    maxCount: 1,
  },
  {
    provider: 'ollama',
    modelId: 'x/z-image-turbo',
    label: 'Z-Image Turbo (Ollama)',
    description: 'Experimental Ollama OpenAI-compatible image model.',
    operations: ['generate'],
    sizes: ['1024x1024', '1344x768', '768x1344'],
    experimental: true,
    supportsSeed: true,
    supportsQuality: true,
    qualityOptions: ['auto', 'high'],
    maxCount: 2,
  },
  {
    provider: 'ollama',
    modelId: 'x/flux2-klein',
    label: 'FLUX.2 Klein (Ollama)',
    description: 'Experimental local Ollama image generation model.',
    operations: ['generate'],
    sizes: ['1024x1024', '1344x768', '768x1344'],
    experimental: true,
    supportsSeed: true,
    maxCount: 2,
  },
];

function isConfigured(provider: PaintingProvider, env: PaintingCatalogEnv) {
  if (provider === 'openai') return Boolean(env.OPENAI_API_KEY);
  if (provider === 'google') return Boolean(env.GOOGLE_GENERATIVE_AI_API_KEY);
  if (provider === 'stability') return Boolean(env.STABILITY_API_KEY);
  if (provider === 'freepik') return Boolean(env.FREEPIK_API_KEY);
  if (provider === 'ollama') return Boolean(env.OLLAMA_BASE_URL);
  return false;
}

export function listConfiguredPaintingModels(env: PaintingCatalogEnv) {
  return ALL_MODELS.filter((model) => isConfigured(model.provider, env));
}

export function getPaintingModelById(provider: PaintingProvider, modelId: string) {
  return ALL_MODELS.find((model) => model.provider === provider && model.modelId === modelId) ?? null;
}

export function getAllPaintingModels() {
  return ALL_MODELS.slice();
}
